### ISSUE TITLE
Some improvements

### ISSUE THREAD

**Issue by igarrido-adalab** [Adalab/modulo-2-evaluacion-intermedia-AnadelaJara#1]
Really cool job @AnadelaJara !!!

Here you have some tips to improve the exercise:

### JavaScript: basic

- [x] Define the logic to count the points of each player
- [x] Use three counter variables: one for user wins, other for computer wins and another for total rounds played. Define them globally and  assign a first value of 0.
- [x] Increment the counter for user wins when the user wins a round (find the correct conditions).
- [x] Increment the counter for computer wins when the computer wins a round (find the correct conditions).
- [x] Increment the round counter always the user clicks on "Jugar" button.
- [x] Show the counters in the proper elements of the page.
- [x] Watch out for constant names used to save DOM references... Do we want to use the DOM reference or that DOM element content (innerHTML/value)?

### JavaScript: advanced

- [ ] Check if the `<select>` has the default option (with no value).
- [x] Check if the round counter has reached the limit of rounds.
- [ ] You are writing many times `"trackEl.innerHTML = 'something';"`, what about making a function that accepts a string as param and paints it into `'trackEl'`?

### Good practices

- [x] Try to use imperative for functions names.
- [x] Try to improve your commits messages. "Add JS" is a bit poor. "Add random number logic" is more explanatory.

### Steps to finish the game (for those far from the solution)

You are close to the exercise solution, but here you have a steps guide to complete it anyway ;)

1. Increment the number of rounds won to which corresponds and write the result into the page.
2. Assign a listener to the button click to execute the previous function.
3. Create other function to check if the players have reached the maximum limit of rounds and call it from the listener function.

### Further challenges

Then you can improve the game as you please, here you have some ideas:

- Show an image with the user and computer selection
- Make the input work when selecting the option.
- Add a reset button that cleans the select, the counter and writes the initial feedback
- Whatever you want!

### Call to action

Let me know if you have any doubts ;)

Go for it!!

> Do not close this issue until your teacher asks you to

**Comment by igarridomorillas** [comment]
Ok!
